services:
  eazybank-mysql-db:
    image: 'mysql:latest'
    restart: always
    environment:
      - 'MYSQL_DATABASE=eazybank-db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3350:3306'
#
#  eazybank-phpmyadmin:
#    image: phpmyadmin:latest
#    restart: always
#    environment:
#      - 'PMA_ARBITRARY=1'
#    ports:
#      - '3351:80'